<!DOCTYPE html>
<html>

<head>
    <title>homework</title>
</head>

<body>
    <table border="4" bgcolor="red">
        <th>Company</th>
        <th>Money</th>
        <th>Popularity</th>
        <th>Best</th>
        <tr>
        </tr>
        <td>Tesla</td>
        <td>1204.01 bil</td>
        <td>8.6/10</td>
        <td>No</td>
        <tr>
        </tr>
        <td>Amazon</td>
        <td>1.105 tril</td>
        <td>9.7/10</td>
        <td>Yes</td>
    </table>
</body>

</html>