<!DOCTYPE html>
<html>

<head>
    <title>Company Basics</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=divice-width">
    <title>Replit</title>
    <link href="style.css" rel="stylesheet" type="text/css" />
    <style>
        th {
            background-color: lightgray;
        }
    </style>
</head>

<body>
    <h2>Company Basics</h2>
    <table border="4" bgcolor="bluefffffff">
        <th>Company</th>
        <th>Money</th>
        <th>Popularity</th>
        <th>Stock value</th>
        <th>Yearly income</th>
        <th>Type</th>
        <tr>
        </tr>
        <td>Tesla</td>
        <td>1204.01 bil</td>
        <td>8.6/10</td>
        <td>360 usd</td>
        <td>97.7 bil</td>
        <td>Car</td>
        <tr>
        </tr>
        <td>Amazon</td>
        <td>1.105 tril</td>
        <td>9.7/10</td>
        <td>226.63 usd</td>
        <td>514 bil</td>
        <td>shopping</td>
        <tr>
        </tr>
        <td>Netflix</td>
        <td>439.56 bil</td>
        <td>8.2/10</td>
        <td>1043.33 usd</td>
        <td>33.72 bil</td>
        <td>Entertainment</td>
        <tr>
        </tr>
        <td>Roblox</td>
        <td>43.35 bil</td>
        <td>9.8/10</td>
        <td>63.64 usd</td>
        <td>2.80 bil</td>
        <td>Gaming</td>
        <tr>
        </tr>
        <td>Apple</td>
        <td>3.56 tril</td>
        <td>9.6/10</td>
        <td>244.87 usd</td>
        <td>93.74 bil</td>
        <td>Tech/phone</td>
        <tr>
        </tr>
        <td>Microsoft</td>
        <td>3.11 tril</td>
        <td>8.8/10</td>
        <td>414.77 usd</td>
        <td>198 bil</td>
        <td>Tech/search engine</td>
        <tr>
        </tr>
        <td>Google</td>
        <td>2.05 tril</td>
        <td>9.8/10</td>
        <td>185.27 usd</td>
        <td>307.39 bil</td>
        <td>Tech/search engine</td>
        <tr>
        </tr>
        <td>Disney</td>
        <td>168.65 bil</td>
        <td>8.2/10</td>
        <td>111.35 usd</td>
        <td>91.36 bil</td>
        <td>Entertainment</td>
        <tr>
        </tr>
        <td>Samsung</td>
        <td>1.2 tril</td>
        <td>7.2/10</td>
        <td>58,700 usd</td>
        <td>245.7 bil</td>
        <td>Tech/phone</td>
        <tr>
        </tr>
        <td>Doordash</td>
        <td>81.6 bil</td>
        <td>8.8/10</td>
        <td>202.25</td>
        <td>8.36 bil</td>
        <td>Food Deliveiry</td>
        <tr>
        </tr>
        <td>Nike</td>
        <td>31 bil</td>
        <td>9.5/10</td>
        <td>77.25 usd</td>
        <td>5.7 bil</td>
        <td>shoes</td>
        <tr>
        </tr>
        <td>Nivida</td>
        <td>3 tril</td>
        <td>7.6/10</td>
        <td>140.11 usd</td>
        <td>29.76 bil</td>
        <td>Tech</td>
        <tr>
        </tr>
        <td>Honda</td>
        <td>42.91 bil</td>
        <td>9.4/10</td>
        <td>27.24 usd</td>
        <td>145.46 bil</td>
        <td>Car</td>
        <tr>
        </tr>
        <td>Meta</td>
        <td>1803.94 bil</td>
        <td>9.7/10</td>
        <td>694.84 usd</td>
        <td>39.089 bil</td>
        <td>Vr</td>
        <tr>
        </tr>
        <td>Walmart</td>
        <td>648 bil</td>
        <td>9.8/10</td>
        <td>97.22 usd</td>
        <td>611 bil</td>
        <td>Shopping</td>
        <tr>
        </tr>
        <td>Chevron</td>
        <td>264.59 bil</td>
        <td>9.2/10</td>
        <td>158.79 usd</td>
        <td>246.252 bil</td>
        <td>gas</td>
        <tr>
        </tr>
        <td>Bank of America</td>
        <td>2.54 tril</td>
        <td>9.6/10</td>
        <td>45.30 usd</td>
        <td>6.67 bil</td>
        <td>Bank</td>
        <tr>
        </tr>
        <td>Xfinity</td>
        <td>130.33 bil</td>
        <td>9.2/10</td>
        <td>36.41 usd</td>
        <td>66.32 bil</td>
        <td>Wifi/Tech</td>
        <tr>
        </tr>
        <td>T-mobile</td>
        <td>190 bil</td>
        <td>9.5/10</td>
        <td>265.40</td>
        <td>3.1 bil</td>
        <td>Wifi/Tech</td>
        <tr>
        </tr>
        <td>Toyota</td>
        <td>256.68 bil</td>
        <td>9.4/10</td>
        <td>180.69 usd</td>
        <td>298 bil</td>
        <td>Car</td>
        <tr>
        </tr>
        <td>Nestle</td>
        <td>221.58 bil</td>
        <td>9.9/10</td>
        <td>91.02 usd</td>
        <td>95.701 bil</td>
        <td>Food</td>
        <tr>
        </tr>
        <td>Ford</td>
        <td>40.171 bil</td>
        <td>9.4/10</td>
        <td>9.28 usd</td>
        <td>17.937 bil</td>
        <td>Car</td>
        <tr>
        </tr>

</html>